command_timeout = 10000

# Inserts a blank line between shell prompts
# add_newline = true

format = """
$git_branch\
$git_state\
$git_status\
$nodejs\
$package\
$directory\
$character"""

right_format = """
$status\
$aws\
$cmd_duration\
$time\
"""

#style = "fg:#e3e5e5 bg:#769ff0"

[directory]
style = "#00B2FF"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = " [$path[$read_only](bg:$style fg:black)](bg:#303030 fg:$style)[](fg:#303030)"
read_only = " "

[git_branch]
#format = "[$branch]($style)"
#style = "bright-black"
#[git_branch]
style = "#d8712c"
format = "[](fg:black bg:$style)[ $symbol$branch](fg:black bg:$style)[](fg:$style)"

#[git_status]
#format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-black) ($ahead_behind$stashed)]($style)"
#style = "cyan"
#conflicted = "​"
#untracked = "​"
#modified = "​"
#staged = "​"
#renamed = "​"
#deleted = "​"
#stashed = "≡"

[git_commit]
style = "#d8712c"
format = "\b[ ](bg:$style)[\\($hash$tag\\)](fg:black bg:$style)[](fg:$style)"

[git_state]
style = "#d8712c"
format = "\b[ ](bg:$style)[ \\($state( $progress_current/$progress_total)\\)](fg:black bg:$style)[](fg:$style)"
#[git_state]
#format = '\([$state( $progress_current/$progress_total)]($style)\) '
#style = "bright-black"


[git_status]
style = "#d8712c"
format = "(\b[ ](bg:$style fg:black)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind[](fg:$style))"
conflicted = "[ ](bold fg:88 bg:#d8712c)[  ${count} ](fg:black bg:#d8712c)"
staged = "[ $count ](fg:black bg:#d8712c)"
modified = "[ ${count} ](fg:black bg:#d8712c)"
renamed = "[ ${count} ](fg:black bg:#d8712c)"
deleted = "[ ${count} ](fg:black bg:#d8712c)"
untracked = "[?${count} ](fg:black bg:#d8712c)"
stashed = "[ ${count} ](fg:black bg:#d8712c)"
ahead = "[ ${count} ](fg:#523333 bg:#d8712c)"
behind = "[ ${count} ](fg:black bg:#d8712c)"
diverged = "[ ](fg:88 bg:#d8712c)[ נּ ](fg:black bg:#d8712c)[ ${ahead_count} ](fg:black bg:#d8712c)[ ${behind_count} ](fg:black bg:#d8712c)"

[cmd_duration]
min_time = 2000
show_milliseconds = false
disabled = false
style = "#f9a600"
format = "[](fg:black bg:#f9a600)[祥$duration](bg:$style fg:black)[](fg:$style)"

[status]
style = 'bg:blue'
symbol = '❌[]'
success_symbol = '✅'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[aws]
format = '[$symbol$profile]($style) '
style = 'bold purple'
symbol = '🅰 '

#[aws]
#style = "bg:#f9a600 fg:black"
#symbol = "☁ "
#format = "[](fg:black bg:#f9a600)[$symbol$profile]($style)[](fg:#f9a600 bg:black)"


#[nodejs]
#format = 'via [🤖 $version](bold green) '
#style = "green"
#format = "[](fg:black bg:#eb9606)[$symbol($version)](fg:black bg:#eb9606)[](fg:#eb9606)"

[time]
disabled = false
style = "#939594"
format = "[$time]($style)"

[character]
success_symbol = ' [➜](bold green)'
error_symbol = ' [➜](bold red)'

[docker_context]
style = "fg:black bg:#eb9606"
symbol = "🐳  "
format = "[](fg:black bg:#eb9606)[$symbol$context]($style)[](fg:#eb9606)"

[golang]
symbol = "ﳑ "
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[helm]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol($version)]($style)[](fg:#eb9606)"

[java]
symbol = " "
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[kotlin]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[kubernetes]
format = "[](fg:black bg:#ad4007)[$symbol$context](fg:black bg:#ad4007)[](fg:#ad4007)"
disabled = false

#[memory_usage]
#style = "#f9a600"
#symbol = " "
#format = "[](fg:black bg:#f9a600)[$symbol$ram](bg:$style fg:black)[](fg:$style)"
#threshold = 95
#disabled = false

[nodejs]
style = "green"
format = "[](fg:black bg:#eb9606)[$symbol($version)](fg:black bg:#eb9606)[](fg:#eb9606)"

[ocaml]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[package]
disabled = true

[php]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[python]
symbol = " "
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$pyenv_prefix$version$virtualenv]($style)[](fg:#eb9606)"

[ruby]
symbol = " "
format = "[](fg:black bg:#eb9606)[$symbol$version](fg:black bg:#eb9606)(fg:black bg:#eb9606)[](fg:#eb9606)"

[rust]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[scala]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[swift]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"

[shell]
fish_indicator = ""
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = ""
format = "[$indicator](fg:#ad4007)"
disabled = false

[shlvl]
symbol = " "
style = "fg:black bg:#ad4007"
format = "[](fg:black bg:#ad4007)[$symbol$shlvl]($style)[](fg:#ad4007)"
disabled = false

[terraform]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$workspace]($style)[](fg:#eb9606)"

[username]
style_user = "#0370C0"
style_root = "#C00311"
format = "[](fg:black bg:$style)[$user](fg:black bg:$style)[](fg:$style)"

[vagrant]
style = "fg:black bg:#eb9606"
format = "[](fg:black bg:#eb9606)[$symbol$version]($style)[](fg:#eb9606)"